### PR TITLE
Lazy load document and window

### PR DESCRIPTION
**Pull request by danielepolencic**
This is a follow-up PR to this: https://github.com/evnbr/regionize/issues/3

With this PR, I can successfully write `Bindery.createRule()` in a node.js script without triggering any error.

### CODE REVIEW

**Comment by evnbr** [comment]
cool, appreciate the pr!

**Comment by danielepolencic** [comment]
@evnbr Is it possible to release this to npm? Happy to wait otherwise.

**Comment by evnbr** [comment]
@danielepolencic whoops thanks for the reminder— done

**Comment by danielepolencic** [comment]
Many thanks!

**Comment by danielepolencic** [comment]
For some reason, `2.3.3` has none of the changes from this PR.
The interfaces are still `{}` and the script fails when loaded in Node.js.
I was wondering if you could check?

**Comment by evnbr** [comment]
@danielepolencic Yeah, my mistake, published from a stale branch without realizing. It looks like bindery doesn't build successfully with the interfaces in #83 — it flushed out some sketchy loose typing in the default set of rules. I'm fixing up this afternoon and will publish a 2.3.4.

**Comment by evnbr** [comment]
2.3.4 should now include these changes

**Comment by danielepolencic** [comment]
it works and it's great. Thanks!

**Pull request merged**
